<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <Nullable>enable</Nullable>
    <LangVersion>latest</LangVersion>
    <ImplicitUsings>enable</ImplicitUsings>
    <AssemblyName>DLSSGManager</AssemblyName>
    <RootNamespace>DLSSGManager</RootNamespace>
    <Version>1.9.3</Version>
    <Product>DLSSG SM86 管理器</Product>
    <AssemblyTitle>DLSSG SM86 管理器</AssemblyTitle>
    <SatelliteResourceLanguages>en</SatelliteResourceLanguages>
    <EnableDefaultApplicationDefinition>false</EnableDefaultApplicationDefinition>
  </PropertyGroup>

  <ItemGroup>
    <ApplicationDefinition Include="App.xaml" SubType="Designer" Generator="MSBuild:Compile" />
  </ItemGroup>

</Project>
