using System.Collections.Generic;

namespace DLSSGManager;

/// <summary>
/// English table. Must contain exactly the keys in <c>Strings.zh.cs</c>; a test asserts this through
/// <see cref="Strings.MissingKeys"/> so a forgotten translation fails the build instead of showing a
/// raw key in the interface.
/// </summary>
public static partial class Strings
{
    private static Dictionary<string, string> English() => new()
    {
        // ── App / common ─────────────────────────────────────────────
        ["App.Name"] = "DLSSG 30-Series Manager",
        ["App.Subtitle"] = "DLSS frame generation for RTX 30 series — per-game configuration, one-click deploy and restore",
        ["Common.Ok"] = "OK",
        ["Common.Cancel"] = "Cancel",
        ["Common.Yes"] = "Yes",
        ["Common.No"] = "No",
        ["Common.Browse"] = "Browse…",
        ["Common.Auto"] = "Auto",
        ["Common.Unknown"] = "Unknown",

        // ── Toolbar ──────────────────────────────────────────────────
        ["Toolbar.ModSource"] = "Mod files:",
        ["Toolbar.Gpu"] = "GPU:",
        ["Toolbar.ScanSteam"] = "Scan Steam library",
        ["Toolbar.ScanFolder"] = "Scan folder…",
        ["Toolbar.UpdateMod"] = "Download / update mod files",
        ["Toolbar.UpdateModTip"] = "Fetches dlssg_for_sm86 from several mirrors and verifies the signature before writing",
        ["Toolbar.AddProxy"] = "Add proxy DLL…",
        ["Toolbar.AddProxyTip"] = "Add a community-built proxy (d3d12.dll, for instance) to the entry-name list so it can be deployed like the bundled ones",
        ["Toolbar.RestartAdmin"] = "Restart as administrator",
        ["Toolbar.AlreadyAdmin"] = "Running as administrator",
        ["Toolbar.OpenDataDir"] = "Open data folder",
        ["Toolbar.ModReady"] = "Ready · {0}",
        ["Toolbar.ModNotReady"] = "Not ready · download mod files first",
        ["Toolbar.ModIncomplete"] = "Incomplete",
        ["Toolbar.ModReadyTip"] = "Proxy entries: {0}",
        ["Toolbar.ModMissingTip"] = "Mod files are missing. Use “Download / update mod files” to fetch them, or see docs/mod-files.md.",
        ["Toolbar.Language"] = "Language",
        ["Toolbar.GpuName"] = "GPU name…",
        ["GpuName.Title"] = "GPU name",
        ["GpuName.Current"] = "Currently reported",
        ["GpuName.Real"] = "Actual hardware",
        ["GpuName.New"] = "New name",
        ["GpuName.Apply"] = "Apply",
        ["GpuName.Restore"] = "Restore real name",
        ["GpuName.NoGpu"] = "No NVIDIA adapter detected; nothing to change.",
        ["GpuName.NoKey"] = "Could not find the display adapter's registry entry.",
        ["GpuName.Empty"] = "The name cannot be empty.",
        ["GpuName.TooLong"] = "The name is too long (127 characters max).",
        ["GpuName.ControlChar"] = "The name must not contain control characters.",
        ["GpuName.Trim"] = "The name must not start or end with whitespace.",
        ["GpuName.WriteFailed"] = "Write failed: {0}",
        ["GpuName.AdminHint"] = "This needs administrator rights: use “Restart as administrator” in the top right, or right-click the exe and choose “Run as administrator”.",
        ["GpuName.Changed"] = "Display name changed to “{0}”. Restart the game/app for it to take effect.",
        ["GpuName.Restored"] = "Display name restored to “{0}”. Restart the game/app for it to take effect.",
        ["GpuName.NoRealName"] = "Could not read the hardware's real name; type it into the box manually.",
        ["GpuName.Note"] = "Some games decide features (including frame generation) from the reported GPU model, which is why the displayed model can be edited here. Only the display name is changed — the hardware and driver are untouched — and “Restore” writes the real name of the physical device back. Requires administrator rights; takes effect after the game/app is restarted.",
        ["Toolbar.Theme"] = "Theme",
        ["Theme.Dark"] = "Dark",
        ["Theme.Light"] = "Light",

        // ── Game list ────────────────────────────────────────────────
        ["List.Title"] = "Games",
        ["List.Add"] = "Add game…",
        ["List.AddTip"] = "Pick a game folder; anti-cheat is checked automatically",
        ["List.Remove"] = "Remove",
        ["List.Empty"] = "Select a game on the left, or scan to add one.",
        ["List.AddedMessage"] = "Added game: {0}",
        ["List.RemoveConfirm"] = "Remove “{0}” from the list?",
        ["List.RemoveWarnDeployed"] = "\n\nNote: this game is still deployed. Removing the entry does not delete files from the game folder — run Restore first.",
        ["List.RemoveTitle"] = "Remove",
        ["List.NewGame"] = "New game",
        ["List.AddFolderTitle"] = "Select the game folder (containing the game executable)",

        // ── Game detail ──────────────────────────────────────────────
        ["Detail.GroupGame"] = "Game",
        ["Detail.Name"] = "Name",
        ["Detail.RenderDir"] = "Render directory",
        ["Detail.BrowseDirTitle"] = "Select the folder containing the rendering executable",
        ["Detail.Detect"] = "Auto-detect",
        ["Detail.ExePath"] = "Launcher",
        ["Detail.BrowseExeTitle"] = "Select the game executable",
        ["Detail.ExeFilter"] = "Executables (*.exe)|*.exe",
        ["Detail.ProxyEntry"] = "Proxy entry",
        ["Detail.ProxyNote"] = "The proxy must sit beside the rendering executable. If another mod already occupies a name, pick a different one; this manager installs one proxy per game.",
        ["Detail.GroupFg"] = "Frame generation (written to dlssg_sm86.ini)",
        ["Detail.Enabled"] = "Enable frame generation (Enabled=0 falls back to the game's own DLSS-G, which does nothing on Ampere)",
        ["Detail.OptimizedTier"] = "Consistency tier",
        ["Detail.OptimizedTierTip"] = "How far the generated image may move from the official runtime: higher is faster and further away. 0 and 1 stay bit-identical; 2/3 are lossy and need the 310.9 build (310.1 falls back to 1).",
        ["Detail.Tier0"] = "0 stock (bit-identical)",
        ["Detail.Tier1"] = "1 bit-identical speedups (recommended)",
        ["Detail.Tier2"] = "2 lossy ~50 dB (310.9 only)",
        ["Detail.Tier3"] = "3 all lossy (fastest)",
        ["Detail.Preset"] = "Render preset",
        ["Detail.PresetTip"] = "DLSS-G UI-recomposition preset, 310.9 builds only. Auto lets the game or the driver profile decide; A forces it off; B forces it on (needs the game to hand DLSS-G both a HUD-less image and a UI plane, which most do not, and then B is a no-op).",
        ["Detail.Router"] = "GPU route (legacy)",
        ["Detail.KernelImage"] = "Kernel image",
        ["Detail.MaxFrames"] = "Frame multiplier",
        ["Detail.LogLevel"] = "Log level",
        ["Detail.HardwareBilinear"] = "Use approximate hardware bilinear sampling (HardwareBilinear=1, SM86 only, changes generated pixels)",
        ["Detail.Diagnostics"] = "Enable diagnostic timings ([Diagnostics]; for troubleshooting, costs performance)",
        ["Detail.Frames2X"] = "2X (up to 1 extra frame)",
        ["Detail.Frames3X"] = "3X (up to 2 extra frames)",
        ["Detail.Frames4X"] = "4X (up to 3 extra frames)",
        ["Detail.Frames5X"] = "5X (up to 4 extra frames)",
        ["Detail.Frames6X"] = "6X (up to 5 extra frames; game support required)",
        ["Detail.Log0"] = "0 · Off",
        ["Detail.Log1"] = "1 · Errors only",
        ["Detail.Log2"] = "2 · Diagnostics",
        ["Detail.Log3"] = "3 · Verbose",
        ["Detail.GroupActions"] = "Actions",
        ["Detail.NoPath"] = "(no path set)",
        ["Detail.LocatedMessage"] = "Located: {0}",
        ["Detail.LocatedNotRenderDir"] = "  Not a render directory; resolved to {0}",
        ["Detail.DetectNeedFolder"] = "Choose an existing folder with “Browse…” first.",
        ["Detail.DetectNoMarker"] = "nvngx_dlssg.dll not found. This game may not support DLSS frame generation.",
        ["Detail.DetectSearching"] = "— Looking for the render directory under {0}",
        ["Detail.SettingSummary"] = "  route {0} / {1} / up to {2}X / approximate sampling {3} / log {4}",
        ["Detail.SettingSummaryModern"] = "  frame gen {0} / tier {1} / preset {2} / up to {3}X / log {4}",
        ["Detail.BackupCount"] = "{0} original file(s) backed up",
        ["Detail.EntriesTaken"] = "Every available entry name is already taken in this game folder (version / winmm / dinput8 / winhttp / dxgi, plus any local entries you added). Pick one manually in the game's settings, or remove the mod occupying it.",

        // ── Actions ──────────────────────────────────────────────────
        ["Action.Deploy"] = "Deploy to this game",
        ["Action.Restore"] = "Restore",
        ["Action.Adopt"] = "Adopt manual install",
        ["Action.Check"] = "Check status",
        ["Action.OpenDir"] = "Open game folder",
        ["Action.Launch"] = "Launch game",
        ["Action.ViewLog"] = "View mod log",
        ["Action.RemoveLogs"] = "Also delete the dlssg_sm86\\logs folder on restore",
        ["Action.DeployAll"] = "Deploy all",
        ["Action.RestoreAll"] = "Restore all",
        ["Action.RefreshAll"] = "Refresh all",
        ["Action.Clear"] = "Clear",
        ["Action.Output"] = "Output",

        // ── Deploy ───────────────────────────────────────────────────
        ["Deploy.Starting"] = "— Deploying {0}",
        ["Deploy.Success"] = "Deployed: {0}",
        ["Deploy.RemoveRedundant"] = "Removed surplus proxy entry {0} (only one is allowed)",
        ["Deploy.StandbyKept"] = "Kept standby proxy {0} (coexistence is normal since 0.3.3; restore cleans it up too)",
        ["Deploy.Done"] = "Deployed {0} + {1} → {2}",
        ["Deploy.Settings"] = "  route {0} / {1} / up to {2}X / approximate sampling {3} / log {4}",
        ["Deploy.On"] = "on",
        ["Deploy.Off"] = "off",
        ["Deploy.BackedUp"] = "  Backed up {0} occupied file(s) → {1}",
        ["Deploy.BackupFile"] = "  Backed up {0} ({1} KB)",
        ["Deploy.Failed"] = "Deployment failed: {0}",
        ["Deploy.NeedDir"] = "Set a valid render directory first.",
        ["Deploy.GameRunning"] = "The game is running. Close it completely before deploying: {0}",
        ["Deploy.SourceUnavailable"] = "Mod file source unusable: {0}{1}",
        ["Deploy.SourceMissingHint"] = " (folder does not exist). Use “Download / update mod files” in the toolbar.",
        ["Deploy.AllProxiesTaken"] = "Every available entry name is already taken in this game folder (version / winmm / dinput8 / winhttp / dxgi, plus any local entries you added). Pick one manually in the game's settings, or remove the mod occupying it.",
        ["Deploy.InvalidProxyName"] = "“{0}” is not a valid entry name. Choose one from the list.",
        ["Deploy.NoPermission"] = "No write permission. Restart the manager as administrator.",
        ["Deploy.ProxyTaken"] = "Entry name {0} is used by another mod. Pick one manually in the game's settings, or remove the mod occupying it.",
        ["Deploy.BlockedKernel"] = "Deployment blocked: {0} ({1}).\n     Kernel-level anti-cheat may block or quarantine the proxy DLL, and a detection may put your account at risk, so an explicit confirmation is required first.\n     The interface asks for that confirmation before deploying; once given, deployment proceeds.",
        ["Deploy.ConfirmTitle"] = "Confirm deployment",
        ["Deploy.BlockedTooltip"] = "This game uses kernel-level anti-cheat: the proxy may be blocked or quarantined, and a detection may be recorded. Deployment asks for confirmation first.",

        ["Restore.Starting"] = "— Restoring {0}",
        ["Restore.None"] = "Nothing to restore.",
        ["Restore.Done"] = "Restore complete, {0} item(s) handled.",
        ["Restore.Removed"] = "Removed {0}",
        ["Restore.IniEdited"] = "Removed {0}: edited by hand, but still this project's file.",
        ["Restore.IniForeign"] = "Kept {0}: not this project's config file.",
        ["Restore.ProxyKept"] = "Kept {0}: contents do not match this record.",
        ["Restore.QuarantinedRemoved"] = "Removed quarantined copy {0}",
        ["Restore.QuarantinedFailed"] = "Could not remove {0}: {1}",
        ["Restore.BackupRestored"] = "Restored {0}",
        ["Restore.BackupLost"] = "Backup missing, skipped: {0}",
        ["Restore.LogsDeleted"] = "Deleted log folder {0}\\",
        ["Restore.Failed"] = "Restore failed: {0}",
        ["Restore.NeedDir"] = "Render directory does not exist; cannot restore.",
        ["Restore.GameRunning"] = "The game is running. Close it completely before restoring: {0}",
        ["Restore.NoRecord"] = "“{0}” has no deployment record.\n\nThe folder will be scanned and only files signed by this project will be removed. Continue?",
        ["Restore.NoRecordTitle"] = "Confirm restore",
        ["Restore.RemoveLogsOption"] = "Also delete the dlssg_sm86\\logs folder",

        ["Adopt.Starting"] = "— Adopting {0}",
        ["Adopt.Failed"] = "Adopt failed: {0}",
        ["Adopt.Confirm"] = "Adopting registers an existing proxy DLL as installed by this manager: one of this project's five entries, or the `d3d12.dll` published as an extra (recognised by its pinned hash).\n\nUse it when you copied the mod in by hand. The record has no original backup, so a later restore can only delete these files by their recorded SHA256.\n\nContinue?",
        ["Adopt.ConfirmTitle"] = "Adopt manual install",
        ["Adopt.Done"] = "Adopted {0}",
        ["Adopt.Note"] = "Note: no original backup exists, because the files were placed by hand.",
        ["Adopt.NoIni"] = " (no INI found)",
        ["Adopt.NotFound"] = "No proxy signed by this project, and no published extra (d3d12.dll), was found in that folder.",
        ["Adopt.AdoptedSuffix"] = " (adopted)",
        ["Adopt.ManualVersion"] = "Unknown",

        ["Batch.DeployConfirm"] = "Deploy to {0} game(s):\n\n{1}\n\nThe games must be closed. Continue?",
        ["Batch.DeployConfirmWithRisk"] = "Deploy to {0} game(s):\n\n{1}\n\n{2} of them use a kernel-level anti-cheat, where the proxy may be blocked or quarantined and a detection may put your account at risk:\n{3}\n\nDeploy to all of them?",
        ["Batch.DeployTitle"] = "Deploy all",
        ["Batch.RestoreConfirm"] = "Remove this project's files from {0} game(s):\n\n{1}\n\nOnly files confirmed to belong to this project are deleted; displaced originals are restored. Continue?",
        ["Batch.RestoreTitle"] = "Restore all",
        ["Batch.DeployStart"] = "— Batch deploy to {0} game(s)",
        ["Batch.RestoreStart"] = "— Batch restore {0} game(s)",
        ["Batch.Result"] = "Batch {0} finished: {1} of {2} succeeded",
        ["Batch.RiskMark"] = " (anti-cheat risk)",
        ["Batch.Deploy"] = "deploy",
        ["Batch.Restore"] = "restore",
        ["Batch.NothingToDeploy"] = "No game to deploy to.",
        ["Batch.NothingToRestore"] = "No deployed game.",
        ["Batch.LastDeploy"] = "Last batch deploy: {0} of {1} succeeded",
        ["Batch.Progress"] = "{0} / {1} done",
        ["Batch.LastRestore"] = "Last batch restore: {0} of {1} succeeded",
        ["Batch.Item"] = "  {0} {1}: {2}",

        // ── Status ───────────────────────────────────────────────────
        ["Status.Deployed"] = "Deployed",
        ["Status.Modified"] = "Modified",
        ["Status.Missing"] = "Files missing",
        ["Status.NotDeployed"] = "Not deployed",
        ["Status.NotChecked"] = "Not checked",
        ["Status.NoRenderDir"] = "No render directory set",
        ["Status.RenderDirMissing"] = "Render directory does not exist",
        ["Status.NotDeployedDetail"] = "Not deployed",
        ["Status.ManualInstall"] = "Found a manual install: {0}. Use “Adopt” to bring it under management.",
        ["Status.DeployedDetail"] = "Mod {0} · {1} · {2}",
        ["Status.IniModified"] = "The INI was modified (perhaps you changed settings in game)",
        ["Status.ProxyMismatch"] = "Proxy DLL does not match the deployment record",
        ["Status.VerifyFailed"] = "Verification failed: {0}",
        ["Status.MissingProxy"] = "{0} is missing",
        ["Status.MissingIni"] = "{0} is missing",
        ["Status.Quarantined"] = "{0} was quarantined by anti-cheat ({1} renamed copies found; {2}). Use “Restore” to clean up.",
        ["Status.StandbyNote"] = "{0} more of this project's proxies are on standby forwarding (normal since 0.3.3; no second pipeline).",
        ["Status.CheckResult"] = "Checked {0}: {1} — {2}",
        ["Status.DeployHint"] = "After deploying, this manager records file fingerprints and only deletes files confirmed to belong to this project. Displaced originals are backed up first.",
        ["Status.Summary"] = "entry {0} · mod {1} · deployed {2}",
        ["Status.SummaryBackups"] = " · {0} original file(s) backed up",
        ["Status.RefreshFailed"] = "Refresh failed: {0}",
        ["Status.NoPermissionHint"] = "Note: if the game is under Program Files, writing needs administrator rights — use the button in the top right.",
        ["Status.DataDir"] = "Data folder: {0}",

        // ── Scan / detection ─────────────────────────────────────────
        ["Scan.Start"] = "— Scanning: {0}",
        ["Scan.SteamLabel"] = "Steam library",
        ["Scan.FolderTitle"] = "Select a folder to scan (a game drive, for example)",
        ["Scan.Checking"] = "Checking {0}",
        ["Scan.Found"] = "Found {0}",
        ["Scan.SourceFolder"] = "Folder scan",
        ["Scan.Done"] = "Scan finished: {0} candidate(s), {1} added.",
        ["Scan.Cancelled"] = "Scan cancelled or failed.",
        ["Scan.Busy"] = "Another operation is running, please wait.",

        // ── Anti-cheat ───────────────────────────────────────────────
        ["Anti.LevelNone"] = "No anti-cheat detected",
        ["Anti.LevelKernel"] = "Kernel-level anti-cheat detected: {0}",
        ["Anti.LevelUser"] = "Anti-cheat detected: {0}",
        ["Anti.ScanFailed"] = "Anti-cheat scan could not complete (folder unreadable)",
        ["Anti.UnknownDriver"] = "Kernel driver (unidentified vendor)",
        ["Anti.Hoyo"] = "miHoYo HoYoKProtect",
        ["Anti.Tencent"] = "Tencent ACE",
        ["Anti.Neac"] = "NetEase NEAC",
        ["Anti.Eac"] = "Easy Anti-Cheat",
        ["Anti.BattlEye"] = "BattlEye",
        ["Anti.GameGuard"] = "nProtect GameGuard",
        ["Anti.Vanguard"] = "Riot Vanguard",
        ["Anti.Xigncode"] = "XIGNCODE3",
        ["Anti.BlockTitle"] = "This game cannot use the mod",
        ["Anti.ThisGame"] = "This game",
        ["Anti.QuotedName"] = "“{0}”",
        ["Anti.BlockBody"] = "{0} uses a kernel-level anti-cheat: {1}\n\nEvidence: {2}\n\nSuch anti-cheat scans the game folder before launch and blocks or quarantines proxy DLLs, which means:\n· the mod cannot work in this game, and the game may report errors;\n· a detection may put your account at risk.\n\nThis manager refuses to deploy to it. If the game supports frame generation natively (an nvngx_dlssg.dll in the folder indicates it does), enable it in the game instead.",
        ["Anti.BatchTitle"] = "Some games cannot use the mod",
        ["Anti.BatchBody"] = "{0} newly added game(s) use a kernel-level anti-cheat, where the mod may be blocked or quarantined:\n\n{1}\n\nDeploying will show a risk prompt and ask for confirmation (a batch lists these games separately); whether to deploy is your decision.\nSelect any game in the list for details.",
        ["Anti.BatchLog"] = "⚠ {0} of the newly added games use kernel-level anti-cheat: {1}",
        ["Anti.ProtectedLog"] = "⚠ {0}: {1} ({2})",
        ["Anti.OverrideTitle"] = "Kernel-level anti-cheat detected",
        ["Anti.OverrideBody"] = "“{0}” uses a kernel-level anti-cheat: {1}\n\nEvidence: {2}\n\nSuch anti-cheat may block or quarantine the proxy DLL, and a detection may put your account at risk — the risk is yours to take.\n\nDeploy anyway?",
        ["Anti.OverrideLog"] = "⚠ User confirmed deployment on a protected game: {0} — {1}",
        ["Anti.CancelLog"] = "Deployment cancelled for {0}: {1} ({2})",
        ["Anti.BannerBody"] = "Kernel-level anti-cheat may block or quarantine the proxy DLL (the bundled entry names are known to be quarantined in Zenless Zone Zero), and a detection may be recorded. Whether to deploy is your decision — the manager asks for confirmation first, and “Restore” cleans up files that were already quarantined.",

        // ── GPU ──────────────────────────────────────────────────────
        ["Gpu.NotFound"] = "No NVIDIA GPU detected",
        ["Gpu.NotFoundAdvice"] = "No NVIDIA GPU detected. This mod needs the NGX/NVAPI/CUDA interfaces provided by an NVIDIA driver.",
        ["Gpu.NoAdapter"] = "Could not enumerate display adapters. This mod needs the NGX/NVAPI/CUDA interfaces provided by an NVIDIA driver.",
        ["Gpu.Driver"] = "driver {0}",
        ["Gpu.DriverUnknown"] = "driver version unknown",
        ["Gpu.NameWithDriver"] = "{0} (driver {1})",
        ["Gpu.AdviceAmpere"] = "Matches this machine: the SM86 route is what the author validated on real hardware.",
        ["Gpu.AdviceAda"] = "This architecture supports DLSS frame generation natively; the mod is usually unnecessary.",
        ["Gpu.AdviceTuring"] = "Turing should use the SM75 route; the author only forward-checked PTX on a 3080 Ti.",
        ["Gpu.AdviceUnknown"] = "Unrecognised model — confirm the route yourself.",
        ["Gpu.Mismatch"] = "⚠ GPU name does not match its hardware ID: the name reads “{0}”, but hardware ID {1} belongs to {2}{3}. The name may have been altered by a tool, which misleads drivers and games. The {2} route {4} was chosen from the hardware ID; restoring the GPU name is recommended.",
        ["Gpu.SeriesAmpere"] = " (RTX 30 series)",
        ["Gpu.MismatchShort"] = "⚠ name doesn’t match the hardware ID; restore the GPU name",
        ["Gpu.RouteShort"] = "route {0}",
        ["Gpu.SeriesTuring"] = " (RTX 20 series)",
        ["Gpu.SeriesAda"] = " (RTX 40 series)",
        ["Gpu.SeriesBlackwell"] = " (RTX 50 series)",

        // ── Fetch ────────────────────────────────────────────────────
        ["Fetch.Starting"] = "Source: {0}",
        ["Fetch.Retrying"] = "Source: {0} (attempt {1})",
        ["Fetch.Downloading"] = "Downloading {0} ({1}/{2})",
        ["Fetch.Extracting"] = "Extracting …",
        ["Fetch.Downloaded"] = "Downloaded {0} MB",
        ["Fetch.DownloadedCount"] = "Downloaded {0} MB ({1}/{2} files)",
        ["Fetch.Updated"] = "Updated {0} file(s) in {1}",
        ["Fetch.PrunedStale"] = "  removed stale entry {0} (no longer published)",
        ["Fetch.UpdatedVersion"] = "Updated to {0} ({1})",
        ["Fetch.UpdatedGeneric"] = "Updated {0} file(s) ({1})",
        ["Fetch.SignatureOk"] = "Signature verified",
        ["Fetch.SkippedOptional"] = "Skipped optional file {0}: {1}",
        ["Fetch.AllFailed"] = "All download sources failed.\n     {0}",
        ["Fetch.Failed"] = "Download failed: {0}",
        ["Fetch.AttemptFailed"] = "[{0}] attempt {1}/{2} failed: {3}",
        ["Fetch.Incomplete"] = "Incomplete content, missing: {0}",
        ["Fetch.Unsigned"] = "Verification failed: these files lack a valid signature from this project — {0}",
        ["Fetch.PinMismatch"] = "Verification failed (mirror source): {0}",
        ["Fetch.PinWarning"] = "Warning: {0}. Source is official GitHub; accepted, but watch for an upstream certificate change.",
        ["Fetch.PinAccepted"] = "The signing certificate differs from the recorded thumbprint ({0}). The source is official GitHub, so it was accepted; update the manager if upstream rotated its certificate.",
        ["Fetch.PinDetail"] = "These files carry an unexpected signing certificate — {0}",
        ["Fetch.ArchiveTooLarge"] = "Archive too large ({0} MB), aborted.",
        ["Fetch.ArchiveTooLarge2"] = "Archive exceeds the size limit, aborted.",
        ["Fetch.ContentTooLarge"] = "Download exceeds the size limit, aborted.",
        ["Fetch.BadArchive"] = "Unexpected archive layout: no content folder found.",
        ["Fetch.EscapeAttempt"] = "An archive entry points outside the destination folder.",
        ["Fetch.UrlRejected"] = "Address not allowed: {0} (if you use a proxy or a hosts-file accelerator, make sure the system proxy is enabled)",
        ["Fetch.RedirectRejected"] = "Redirect target not allowed: {0}",
        ["Fetch.HttpFailed"] = "Request failed (HTTP {1}): {0}",
        ["Fetch.ProgressFiles"] = "{0} · file {1}/{2}",
        ["Fetch.ProgressArchive"] = "{0} · archive",
        ["Fetch.Pause"] = "Pause",
        ["Fetch.Resume"] = "Resume",
        ["Fetch.PauseTip"] = "Pauses once the current file finishes; to switch sources, cancel and pick again",
        ["Fetch.Cancel"] = "Cancel",
        ["Fetch.CancelTip"] = "Abort the download. Nothing unverified is written to the mod folder - cancel and pick another source.",
        ["Fetch.Cancelled"] = "Download cancelled. Use 'Download / update Mod files' to pick another source and retry.",
        ["Fetch.RedirectNoTarget"] = "Redirect has no target address.",
        ["Fetch.RedirectTooMany"] = "Too many redirects.",
        ["Fetch.UnknownFilter"] = "Unrecognised source filter “{0}”; using all sources. Valid values: {1}",
        ["Fetch.SourceCodeload"] = "GitHub archive (codeload)",
        ["Fetch.SourceZipball"] = "GitHub API (zipball)",
        ["Fetch.SourceRaw"] = "GitHub raw files",
        ["Fetch.SourceJsDelivr"] = "jsDelivr CDN mirror",
        ["Fetch.SourceGhProxy"] = "gh-proxy (China accelerator)",
        ["Fetch.SourceGhFast"] = "ghfast (China accelerator)",
        ["Fetch.Note.codeload"] = "One request, about 28 MB, usually the fastest",
        ["Fetch.Note.zipball"] = "The same content as the archive, through the API entry point",
        ["Fetch.Note.raw"] = "Per-file, about 75 MB, a different network path from the two above",
        ["Fetch.Note.jsdelivr"] = "A public CDN, usable when GitHub is unreachable",
        ["Fetch.Note.ghproxy"] = "China-based accelerator; measured fastest, handles both archive and per-file",
        ["Fetch.Note.ghfast"] = "China-based accelerator, per-file download only",
        ["Fetch.FailureItem"] = "{0}: {1}",
        ["Fetch.SingleSourceFailed"] = "The chosen source failed.\n     {0}\n\nTry another source, or pick “Automatic” to let it try each in turn.",
        ["Fetch.PickerTitle"] = "Choose a download source",
        ["Fetch.PickerPrompt"] = "Where should the mod files be downloaded from?",
        ["Fetch.PickerAuto"] = "Automatic (try every source in turn)",
        ["Fetch.PickerAutoNote"] = "Recommended. Falls back to the next source when one is unavailable.",
        ["Fetch.PickerSingleNote"] = "Uses only the chosen source; no fallback on failure.",
        ["Fetch.PickerOfficial"] = "official",
        ["Fetch.PickerMirror"] = "mirror",
        ["Fetch.PickerDownload"] = "Download",
        ["Fetch.Confirm"] = "The dlssg_for_sm86 files will be downloaded into:\n\n{0}\n\nSources are tried in order (GitHub archive / API / raw files, plus the jsDelivr mirror), all over HTTPS, switching automatically on failure. The download is signature-verified before anything is written.\n\nContinue?",
        ["Fetch.ConfirmTitle"] = "Update mod files",
        ["Fetch.StartLog"] = "— Updating mod files from GitHub",
        ["Fetch.AutoStart"] = "— First start: detecting the published version and fetching the mod files → {0}",
        ["Fetch.AutoDetected"] = "  newest published version: {0}",
        ["Fetch.AutoFailed"] = "The automatic fetch did not succeed: {0}\n\nThe program works as usual; use “Download / update mod files” in the toolbar to retry.",
        ["Fetch.DoneTitle"] = "Update complete",
        ["Fetch.DoneTitleFirst"] = "Download complete",
        ["Fetch.DoneBody"] = "{0}\n\nIf the mod has new settings, re-deploy each game to write them.",
        ["Fetch.DoneBodyFirst"] = "{0}\n\nNext, use “Scan Steam library” or “Add game…” to start deploying.",
        ["Fetch.NotReadyLog"] = "Mod file source not ready: mod files have not been fetched. Use “Download / update mod files”.",
        ["Fetch.IncompleteLog"] = "Mod file source incomplete: {0}",

        // ── Adding a proxy DLL (an entry the user supplies)───────────
        ["Proxy.AddTitle"] = "Add proxy DLL",
        ["Proxy.AddFilter"] = "DLL files (*.dll)|*.dll",
        ["Proxy.AddNeedSource"] = "Fetch the mod files first (“Download / update mod files” in the toolbar); the proxy is stored beside them.",
        ["Proxy.AddNeedDll"] = "Choose a .dll file.",
        ["Proxy.AddFileMissing"] = "File does not exist: {0}",
        ["Proxy.AddReserved"] = "“{0}” is one of this project's own entry names and cannot be replaced.",
        ["Proxy.AddUnknownName"] = "“{0}” is not one of the known entry names (version / winmm / dinput8 / winhttp / dxgi / d3d12). Games rarely load anything else, so deploying it will most likely do nothing.\n\nAdd it anyway?",
        ["Proxy.Added"] = "Added proxy entry {0} → {1}",
        ["Proxy.AddedFile"] = "  wrote {0} ({1} KB)",
        ["Proxy.AddedSigner"] = "  signer: {0}",
        ["Proxy.AddedUnsigned"] = "  unsigned or signature invalid (a local file's origin is yours to vouch for)",
        ["Proxy.AddReplaced"] = "  replaced the existing local proxy {0}",
        ["Proxy.AddFailed"] = "Could not add the file: {0}",
        ["Proxy.ImportedSuffix"] = " (extra entry)",

        // ── Mod source ───────────────────────────────────────────────
        ["ModSource.DirMissing"] = "folder does not exist",
        ["ModSource.IniMissing"] = "missing {0}",
        ["ModSource.NoDll"] = "no proxy DLL found (version.dll or altnative\\*.dll)",
        ["ModSource.IniMissingAndNoDll"] = "missing {0}, and no proxy DLL found",
        ["ModSource.IniMissingAt"] = "missing {0}",
        ["ModSource.UnknownVersion"] = "Unknown",

        // ── Shell path validation (internal reasons)──────────────────
        ["Path.Empty"] = "path is empty",
        ["Path.TooLong"] = "path is too long",
        ["Path.Whitespace"] = "path has leading or trailing whitespace",
        ["Path.ControlChar"] = "path contains a control character",
        ["Path.Quote"] = "path contains a quote",
        ["Path.NotAbsolute"] = "path is not absolute",
        ["Path.Invalid"] = "path is invalid: {0}",
        ["Path.Missing"] = "path does not exist",
        ["Path.NotFile"] = "not a file",
        ["Path.NotExecutable"] = "not an executable",

        // ── Errors ───────────────────────────────────────────────────
        ["Error.Unhandled"] = "An unhandled error occurred:\n\n{0}\n\nDetails have been written to the log.",
        ["Error.UnhandledTitle"] = "DLSSG 30-Series Manager",
        ["Error.FetchFailed"] = "Could not fetch the mod files:\n\n{0}\n\nYou can retry from the interface later.",
        ["Error.FetchException"] = "Error while fetching mod files:\n\n{0}",
        ["Error.ElevationCancelled"] = "Elevation was cancelled or failed. You can also right-click the exe and choose “Run as administrator”.",
        ["Error.DirNotFound"] = "Folder does not exist.",
        ["Error.DirOpenFailed"] = "Folder does not exist or cannot be opened.",
        ["Error.LaunchFailed"] = "Launch failed: set a valid launcher path first.",
        ["Error.NoModLog"] = "No mod log yet. Set the game's log level to 2 and start the game to generate one.",
        ["Error.LogOpened"] = "Opened the latest log: {0}",
        ["Error.CannotOpenDataDir"] = "Cannot open the data folder: {0}",
        ["Error.Launched"] = "Launched {0}",
    };
}
