using System.Collections.Generic;

namespace DLSSGManager;

/// <summary>
/// Simplified Chinese table. Keys are grouped by area with a dotted prefix so a key's home is obvious
/// in review; the English table in <c>Strings.en.cs</c> must contain exactly the same keys, which a
/// test asserts via <see cref="Strings.MissingKeys"/>.
/// </summary>
public static partial class Strings
{
    private static Dictionary<string, string> ChineseSimplified() => new()
    {
        // ── 应用与通用 ────────────────────────────────────────────────
        ["App.Name"] = "DLSSG 30 系管理器",
        ["App.Subtitle"] = "为 RTX 30 系添加 DLSS 帧生成：按游戏独立配置，一键部署与恢复",
        ["Common.Ok"] = "确定",
        ["Common.Cancel"] = "取消",
        ["Common.Yes"] = "是",
        ["Common.No"] = "否",
        ["Common.Browse"] = "浏览…",
        ["Common.Auto"] = "自动",
        ["Common.Unknown"] = "未知",

        // ── 工具条 ───────────────────────────────────────────────────
        ["Toolbar.ModSource"] = "Mod 文件源：",
        ["Toolbar.Gpu"] = "显卡：",
        ["Toolbar.ScanSteam"] = "扫描 Steam 库",
        ["Toolbar.ScanFolder"] = "扫描文件夹…",
        ["Toolbar.UpdateMod"] = "下载 / 更新 Mod 文件",
        ["Toolbar.UpdateModTip"] = "从多个下载源获取 dlssg_for_sm86，下载后校验签名",
        ["Toolbar.AddProxy"] = "添加代理 DLL…",
        ["Toolbar.AddProxyTip"] = "把社区构建的代理（例如 d3d12.dll）加入入口名列表，之后可像自带入口一样部署到游戏",
        ["Toolbar.RestartAdmin"] = "以管理员身份重启",
        ["Toolbar.AlreadyAdmin"] = "已是管理员",
        ["Toolbar.OpenDataDir"] = "打开数据目录",
        ["Toolbar.ModReady"] = "可用 · {0}",
        ["Toolbar.ModNotReady"] = "未就绪 · 请先获取 Mod 文件",
        ["Toolbar.ModIncomplete"] = "文件不完整",
        ["Toolbar.ModReadyTip"] = "代理入口：{0}",
        ["Toolbar.ModMissingTip"] = "缺少 Mod 文件。点右侧「下载 / 更新 Mod 文件」自动获取，详见 docs/mod-files.md。",
        ["Toolbar.Language"] = "语言",
        ["Toolbar.GpuName"] = "显卡名称…",
        ["GpuName.Title"] = "显卡名称",
        ["GpuName.Current"] = "当前显示名称",
        ["GpuName.Real"] = "硬件真实名称",
        ["GpuName.New"] = "新名称",
        ["GpuName.Apply"] = "应用",
        ["GpuName.Restore"] = "还原为真实名称",
        ["GpuName.NoGpu"] = "没有检测到 NVIDIA 显卡，无需修改。",
        ["GpuName.NoKey"] = "没有找到显卡的注册表项。",
        ["GpuName.Empty"] = "名称不能为空。",
        ["GpuName.TooLong"] = "名称太长（最多 127 个字符）。",
        ["GpuName.ControlChar"] = "名称里不能包含控制字符。",
        ["GpuName.Trim"] = "名称首尾不能有空白。",
        ["GpuName.WriteFailed"] = "写入失败：{0}",
        ["GpuName.AdminHint"] = "修改需要管理员权限：点右上角「以管理员身份重启」，或右键 exe 选「以管理员身份运行」。",
        ["GpuName.Changed"] = "已把显卡显示名称改为「{0}」。重启游戏/应用后生效。",
        ["GpuName.Restored"] = "已把显卡显示名称还原为「{0}」。重启游戏/应用后生效。",
        ["GpuName.NoRealName"] = "读不到硬件的真实名称，请在输入框里手动填写。",
        ["GpuName.Note"] = "说明：有些游戏按显卡型号决定功能（包括帧生成），所以这里允许修改 Windows 显示的型号。只改显示名称，不动硬件和驱动；「还原」会把物理设备的真实名称写回去。需要管理员权限，重启游戏/应用后生效。",
        ["Toolbar.Theme"] = "主题",
        ["Theme.Dark"] = "深色",
        ["Theme.Light"] = "浅色",

        // ── 游戏列表 ─────────────────────────────────────────────────
        ["List.Title"] = "游戏列表",
        ["List.Add"] = "添加游戏…",
        ["List.AddTip"] = "选择游戏文件夹，添加时自动检测反作弊",
        ["List.Remove"] = "移除",
        ["List.Empty"] = "从左侧选择一款游戏，或先扫描添加。",
        ["List.AddedMessage"] = "已添加游戏：{0}",
        ["List.RemoveConfirm"] = "从列表移除「{0}」？",
        ["List.RemoveWarnDeployed"] = "\n\n注意：该游戏仍处于部署状态。移除条目不会删除游戏目录里的文件；请先执行「一键恢复」。",
        ["List.RemoveTitle"] = "移除",
        ["List.NewGame"] = "新游戏",
        ["List.AddFolderTitle"] = "选择游戏文件夹（包含游戏主程序的目录）",

        // ── 游戏详情 ─────────────────────────────────────────────────
        ["Detail.GroupGame"] = "游戏",
        ["Detail.Name"] = "名称",
        ["Detail.RenderDir"] = "渲染目录",
        ["Detail.BrowseDirTitle"] = "选择包含游戏渲染 EXE 的目录",
        ["Detail.Detect"] = "自动检测",
        ["Detail.ExePath"] = "启动程序",
        ["Detail.BrowseExeTitle"] = "选择游戏主程序",
        ["Detail.ExeFilter"] = "可执行文件 (*.exe)|*.exe",
        ["Detail.ProxyEntry"] = "代理入口",
        ["Detail.ProxyNote"] = "说明：代理入口必须放在渲染 EXE 旁。若某名称已被其他 Mod 占用，换一个入口即可；本管理器每个游戏只装一个代理。",
        ["Detail.GroupFg"] = "插帧配置（写入 dlssg_sm86.ini）",
        ["Detail.Enabled"] = "启用帧生成（Enabled=0 时改用游戏自带的 DLSS-G，Ampere 上不会有效果）",
        ["Detail.OptimizedTier"] = "一致性档位",
        ["Detail.OptimizedTierTip"] = "允许生成的画面偏离官方运行库多远：数字越大越快、离官方画面越远。0 和 1 都逐位一致；2/3 有损，且需要 310.9 构建（310.1 上自动退回 1）。",
        ["Detail.Tier0"] = "0 原厂（逐位一致）",
        ["Detail.Tier1"] = "1 逐位一致加速（推荐）",
        ["Detail.Tier2"] = "2 有损 ~50dB（仅 310.9）",
        ["Detail.Tier3"] = "3 全部有损（最快）",
        ["Detail.Preset"] = "渲染预设",
        ["Detail.PresetTip"] = "DLSS-G 的 UI 重组预设，仅 310.9 版本生效。Auto 交给游戏/驱动决定；A 强制关闭；B 强制开启（需要游戏同时提供无 HUD 画面和 UI 层，多数游戏不满足，此时 B 等于没设）。",
        ["Detail.Router"] = "显卡路由（旧版）",
        ["Detail.KernelImage"] = "内核镜像",
        ["Detail.MaxFrames"] = "倍率上限",
        ["Detail.LogLevel"] = "日志级别",
        ["Detail.HardwareBilinear"] = "使用近似硬件双线性采样（HardwareBilinear=1，仅 SM86，会改变生成像素）",
        ["Detail.Diagnostics"] = "启用诊断计时（[Diagnostics] 段，排查用，会影响性能）",
        ["Detail.Frames2X"] = "2X（最多额外 1 帧）",
        ["Detail.Frames3X"] = "3X（最多额外 2 帧）",
        ["Detail.Frames4X"] = "4X（最多额外 3 帧）",
        ["Detail.Frames5X"] = "5X（最多额外 4 帧）",
        ["Detail.Frames6X"] = "6X（最多额外 5 帧，需游戏支持）",
        ["Detail.Log0"] = "0 · 关闭",
        ["Detail.Log1"] = "1 · 仅错误",
        ["Detail.Log2"] = "2 · 运行诊断",
        ["Detail.Log3"] = "3 · 详细日志",
        ["Detail.GroupActions"] = "操作",
        ["Detail.NoPath"] = "(未设置路径)",
        ["Detail.LocatedMessage"] = "已定位：{0}",
        ["Detail.LocatedNotRenderDir"] = "  该目录不是渲染目录，已定位到 {0}",
        ["Detail.DetectNeedFolder"] = "请先「浏览…」选一个存在的目录，再自动定位。",
        ["Detail.DetectNoMarker"] = "未找到 nvngx_dlssg.dll。该游戏可能不支持 DLSS 帧生成。",
        ["Detail.DetectSearching"] = "— 在 {0} 中查找渲染目录",
        ["Detail.SettingSummary"] = "  路由 {0} / {1} / 最大 {2}X / 近似采样 {3} / 日志 {4}",
        ["Detail.SettingSummaryModern"] = "  帧生成 {0} / 档位 {1} / 预设 {2} / 最大 {3}X / 日志 {4}",
        ["Detail.BackupCount"] = "已备份 {0} 个原文件",
        ["Detail.EntriesTaken"] = "可用入口名在游戏目录里都已被占用（version / winmm / dinput8 / winhttp / dxgi，以及你添加的本地入口）。请在该游戏的设置里手动指定一个入口名，或先移除占用它的 Mod。",

        // ── 操作按钮 ─────────────────────────────────────────────────
        ["Action.Deploy"] = "部署到该游戏",
        ["Action.Restore"] = "一键恢复",
        ["Action.Adopt"] = "接管手工安装",
        ["Action.Check"] = "检查状态",
        ["Action.OpenDir"] = "打开游戏目录",
        ["Action.Launch"] = "启动游戏",
        ["Action.ViewLog"] = "查看 Mod 日志",
        ["Action.RemoveLogs"] = "恢复时一并删除 dlssg_sm86\\logs 日志目录",
        ["Action.DeployAll"] = "全部部署",
        ["Action.RestoreAll"] = "全部恢复",
        ["Action.RefreshAll"] = "刷新全部状态",
        ["Action.Clear"] = "清空",
        ["Action.Output"] = "运行输出",

        // ── 部署 ─────────────────────────────────────────────────────
        ["Deploy.Starting"] = "— 部署 {0}",
        ["Deploy.Success"] = "部署完成：{0}",
        ["Deploy.RemoveRedundant"] = "移除多余的代理入口 {0}（本项目只允许保留一个）",
        ["Deploy.StandbyKept"] = "保留待机代理 {0}（0.3.3+ 共存属正常，恢复时会一并清理）",
        ["Deploy.Done"] = "已部署 {0} + {1} → {2}",
        ["Deploy.Settings"] = "  路由 {0} / {1} / 最大 {2}X / 近似采样 {3} / 日志 {4}",
        ["Deploy.On"] = "开",
        ["Deploy.Off"] = "关",
        ["Deploy.BackedUp"] = "  已备份被占用的原文件 {0} 个 → {1}",
        ["Deploy.BackupFile"] = "  备份 {0}（{1} KB）",
        ["Deploy.Failed"] = "部署失败：{0}",
        ["Deploy.RollbackRestored"] = "  已回滚 {0}：原文件已还原",
        ["Deploy.RollbackRemoved"] = "  已回滚 {0}：本次写入的文件已删除",
        ["Deploy.RollbackFailed"] = "  回滚失败：{0}（{1}）",
        ["Deploy.RollbackNoSnapshot"] = "  回滚失败：{0} 没有可用快照，请手工检查该文件",
        ["Deploy.NeedDir"] = "请先设置有效的渲染目录。",
        ["Deploy.GameRunning"] = "游戏正在运行，请完全退出后再部署：{0}",
        ["Deploy.SourceUnavailable"] = "Mod 文件源不可用：{0}{1}",
        ["Deploy.SourceMissingHint"] = "（目录不存在）。请点工具条上的「下载 / 更新 Mod 文件」获取。",
        ["Deploy.AllProxiesTaken"] = "可用入口名在游戏目录里都已被占用（version / winmm / dinput8 / winhttp / dxgi，以及你添加的本地入口）。请在该游戏的设置里手动指定一个入口名，或先移除占用它的 Mod。",
        ["Deploy.InvalidProxyName"] = "代理名 \"{0}\" 不是有效的入口名。请从下拉列表中选择。",
        ["Deploy.NoPermission"] = "没有写入权限。请用管理员身份重新启动本管理器。",
        ["Deploy.ProxyTaken"] = "入口名 {0} 已被其他 Mod 使用。请在该游戏的设置里手动指定一个入口名，或先移除占用它的 Mod。",
        ["Deploy.BlockedKernel"] = "已阻止部署：{0}（{1}）。\n     内核级反作弊可能拦截并隔离代理 DLL，检测记录也可能危及账号，所以需要明确确认后才能部署。\n     在界面上确认部署时程序会先弹出风险提示；确认后即可继续。",
        ["Deploy.ConfirmTitle"] = "确认部署",
        ["Deploy.BlockedTooltip"] = "该游戏带有内核级反作弊：反作弊可能拦截并隔离代理 DLL，也可能记录检测信息。部署前会要求你确认。",

        ["Restore.Starting"] = "— 恢复 {0}",
        ["Restore.None"] = "没有需要恢复的文件。",
        ["Restore.Done"] = "恢复完成，处理 {0} 项。",
        ["Restore.Removed"] = "已移除 {0}",
        ["Restore.IniEdited"] = "移除 {0}：内容已被手工修改，仍属本项目文件。",
        ["Restore.IniForeign"] = "保留 {0}：不是本项目的配置文件，未删除。",
        ["Restore.ProxyKept"] = "保留 {0}：内容与本记录不符，未删除。",
        ["Restore.QuarantinedRemoved"] = "已清理被隔离的副本 {0}",
        ["Restore.QuarantinedFailed"] = "无法清理 {0}：{1}",
        ["Restore.BackupRestored"] = "已还原 {0}",
        ["Restore.BackupLost"] = "备份文件已丢失，跳过还原：{0}",
        ["Restore.BackupHashMismatch"] = "备份哈希不符，拒绝还原：{0}",
        ["Restore.BackupNoHash"] = "备份缺少哈希记录，拒绝还原：{0}",
        ["Restore.BackupUnsafeName"] = "备份记录的文件名不安全，拒绝还原：{0}",
        ["Restore.LogsDeleted"] = "已删除日志目录 {0}\\",
        ["Restore.Failed"] = "恢复失败：{0}",
        ["Restore.NeedDir"] = "渲染目录不存在，无法恢复。",
        ["Restore.GameRunning"] = "游戏正在运行，请完全退出后再恢复：{0}",
        ["Restore.NoRecord"] = "「{0}」没有部署记录。\n\n将扫描该目录，只删除签名属于本项目的文件（若有）。继续吗？",
        ["Restore.NoRecordTitle"] = "确认恢复",
        ["Restore.RemoveLogsOption"] = "恢复时一并删除 dlssg_sm86\\logs 日志目录",

        ["Adopt.Confirm"] = "接管会把当前目录里已存在的代理 DLL 登记为「由本管理器安装」：本项目的 5 个入口，或随附加入口分发的 `d3d12.dll`（按固定哈希识别）。\n\n适用于你之前手工复制过 Mod 的情况。接管记录不含原始备份，之后恢复只能按记录里的 SHA256 删除这些文件。\n\n继续吗？",
        ["Adopt.Starting"] = "— 接管 {0}",
        ["Adopt.Failed"] = "接管失败：{0}",
        ["Adopt.ConfirmTitle"] = "接管手工安装",
        ["Adopt.Done"] = "已接管 {0}",
        ["Adopt.Note"] = "注意：接管记录里没有原始备份，因为文件是手工放入的。",
        ["Adopt.NoIni"] = "（未找到 INI）",
        ["Adopt.NotFound"] = "该目录里没有本项目签名的代理，也没有已分发的附加入口（d3d12.dll）。",
        ["Adopt.AdoptedSuffix"] = "（接管）",
        ["Adopt.ManualVersion"] = "未知",

        ["Batch.DeployConfirm"] = "将为 {0} 款游戏部署本项目：\n\n{1}\n\n游戏必须处于完全退出状态。继续吗？",
        ["Batch.DeployConfirmWithRisk"] = "将为 {0} 款游戏部署本项目：\n\n{1}\n\n其中 {2} 款带有内核级反作弊，部署可能被拦截或隔离，检测记录也可能危及账号：\n{3}\n\n确定全部部署吗？",
        ["Batch.DeployTitle"] = "全部部署",
        ["Batch.RestoreConfirm"] = "将从 {0} 款游戏中移除本项目文件：\n\n{1}\n\n只删除确认属于本项目的文件，被占用的原文件会还原。继续吗？",
        ["Batch.RestoreTitle"] = "全部恢复",
        ["Batch.DeployStart"] = "— 批量部署 {0} 款游戏",
        ["Batch.RestoreStart"] = "— 批量恢复 {0} 款游戏",
        ["Batch.Result"] = "批量{0}完成：成功 {1} / {2}",
        ["Batch.RiskMark"] = "（反作弊风险）",
        ["Batch.Deploy"] = "部署",
        ["Batch.Restore"] = "恢复",
        ["Batch.NothingToDeploy"] = "没有可部署的游戏。",
        ["Batch.NothingToRestore"] = "没有已部署的游戏。",
        ["Batch.LastDeploy"] = "上次批量部署：成功 {0} / {1}",
        ["Batch.Progress"] = "进行中 {0} / {1}",
        ["Batch.LastRestore"] = "上次批量恢复：成功 {0} / {1}",
        ["Batch.Item"] = "  {0} {1}：{2}",

        // ── 状态 ─────────────────────────────────────────────────────
        ["Status.Deployed"] = "已部署",
        ["Status.Modified"] = "已被改动",
        ["Status.Missing"] = "文件缺失",
        ["Status.NotDeployed"] = "未部署",
        ["Status.NotChecked"] = "未检查",
        ["Status.NoRenderDir"] = "未设置渲染目录",
        ["Status.RenderDirMissing"] = "渲染目录不存在",
        ["Status.NotDeployedDetail"] = "未部署",
        ["Status.ManualInstall"] = "检测到手工安装的 {0}，可点「接管」纳入管理",
        ["Status.DeployedDetail"] = "Mod {0} · {1} · {2}",
        ["Status.IniModified"] = "INI 已被修改（可能是你在游戏里改过配置）",
        ["Status.ProxyMismatch"] = "代理 DLL 与部署记录不一致",
        ["Status.VerifyFailed"] = "校验失败：{0}",
        ["Status.MissingProxy"] = "{0} 不存在",
        ["Status.MissingIni"] = "{0} 不存在",
        ["Status.Quarantined"] = "{0} 已被反作弊隔离（发现 {1} 个被改名的副本，{2}）。点「一键恢复」可清理残留。",
        ["Status.StandbyNote"] = "另有 {0} 个本项目代理在待机转发（0.3.3 起属正常，不会重复插帧）。",
        ["Status.CheckResult"] = "检查 {0}：{1} — {2}",
        ["Status.DeployHint"] = "部署后本管理器会记录文件指纹，恢复时只删除确认属于本项目的文件；被占用的原文件会先备份。",
        ["Status.Summary"] = "入口 {0} · Mod {1} · 部署于 {2}",
        ["Status.SummaryBackups"] = " · 已备份 {0} 个原文件",
        ["Status.RefreshFailed"] = "刷新状态失败：{0}",
        ["Status.NoPermissionHint"] = "提示：游戏若装在 Program Files 下，写入需要管理员权限，可用右上角按钮重启。",
        ["Status.DataDir"] = "数据目录：{0}",

        // ── 扫描与探测 ───────────────────────────────────────────────
        ["Scan.Start"] = "— 开始扫描：{0}",
        ["Scan.SteamLabel"] = "Steam 库",
        ["Scan.FolderTitle"] = "选择要扫描的文件夹（例如某个游戏盘）",
        ["Scan.Checking"] = "检查 {0}",
        ["Scan.Found"] = "找到 {0}",
        ["Scan.SourceFolder"] = "目录扫描",
        ["Scan.Done"] = "扫描完成：发现 {0} 个候选，新增 {1} 款。",
        ["Scan.Cancelled"] = "扫描已取消或失败。",
        ["Scan.Busy"] = "有操作正在进行，请稍候。",

        // ── 反作弊 ───────────────────────────────────────────────────
        ["Anti.LevelNone"] = "未检测到反作弊组件",
        ["Anti.LevelKernel"] = "检测到内核级反作弊：{0}",
        ["Anti.LevelUser"] = "检测到反作弊：{0}",
        ["Anti.ScanFailed"] = "反作弊检测未能完成（目录不可读）",
        ["Anti.UnknownDriver"] = "内核驱动（未识别厂商）",
        ["Anti.Hoyo"] = "米哈游 HoYoKProtect",
        ["Anti.Tencent"] = "腾讯 ACE",
        ["Anti.Neac"] = "网易 NEAC",
        ["Anti.Eac"] = "Easy Anti-Cheat",
        ["Anti.BattlEye"] = "BattlEye",
        ["Anti.GameGuard"] = "nProtect GameGuard",
        ["Anti.Vanguard"] = "Riot Vanguard",
        ["Anti.Xigncode"] = "XIGNCODE3",
        ["Anti.BlockTitle"] = "该游戏无法使用本 Mod",
        ["Anti.ThisGame"] = "该游戏",
        ["Anti.QuotedName"] = "「{0}」",
        ["Anti.BlockBody"] = "{0}带有内核级反作弊：{1}\n\n证据：{2}\n\n这类反作弊会在游戏启动前扫描游戏目录，可能拦截并隔离代理 DLL，也可能记录检测信息：\n· 本项目自带的入口名在这种游戏上通常会被隔离（绝区零的 HoYoKProtect 就是这样）；\n· 社区构建的其他入口名有些能存活（例如 d3d12.dll），但同样有账号风险。\n\n程序不会替你决定：单独部署前会要求确认，批量部署会跳过它。如果游戏自带帧生成（目录里有 nvngx_dlssg.dll 就说明支持），也可以直接在游戏内开启。",
        ["Anti.BatchTitle"] = "有游戏无法使用本 Mod",
        ["Anti.BatchBody"] = "新增的 {0} 款游戏带有内核级反作弊，本 Mod 在这些游戏上可能被拦截或隔离：\n\n{1}\n\n部署时程序会提示风险并要求你确认（批量部署会把这些游戏单独列出来），是否部署由你决定。\n在列表里选中任一游戏可以看到详细信息。",
        ["Anti.BatchLog"] = "⚠ 新增游戏中 {0} 款带有内核级反作弊：{1}",
        ["Anti.ProtectedLog"] = "⚠ {0}：{1}（{2}）",
        ["Anti.OverrideTitle"] = "检测到内核级反作弊",
        ["Anti.OverrideBody"] = "「{0}」带有内核级反作弊：{1}\n\n证据：{2}\n\n这类反作弊可能拦截并隔离代理 DLL，也可能记录检测信息，风险自负。\n\n确定仍要部署吗？",
        ["Anti.OverrideLog"] = "⚠ 用户确认在受保护游戏上部署：{0} — {1}",
        ["Anti.CancelLog"] = "已取消部署 {0}：{1}（{2}）",
        ["Anti.BannerBody"] = "内核级反作弊可能在游戏启动前拦截并隔离代理 DLL（自带入口名在绝区零上已被证实会被隔离），也可能记录检测信息。是否部署由你决定——程序会先要求确认；「一键恢复」可清理已被隔离的残留文件。",

        // ── 显卡 ─────────────────────────────────────────────────────
        ["Gpu.NotFound"] = "未检测到 NVIDIA 显卡",
        ["Gpu.NotFoundAdvice"] = "未检测到 NVIDIA 显卡。本 Mod 需要 NVIDIA 驱动提供的 NGX/NVAPI/CUDA 接口。",
        ["Gpu.NoAdapter"] = "未能枚举显示适配器。本 Mod 需要 NVIDIA 驱动提供的 NGX/NVAPI/CUDA 接口。",
        ["Gpu.Driver"] = "驱动 {0}",
        ["Gpu.DriverUnknown"] = "驱动版本未知",
        ["Gpu.NameWithDriver"] = "{0}（驱动 {1}）",
        ["Gpu.AdviceAmpere"] = "与本机匹配：SM86 路由即作者实卡验证的路径。",
        ["Gpu.AdviceAda"] = "该架构原生支持 DLSS 帧生成，通常不需要本 Mod。",
        ["Gpu.AdviceTuring"] = "Turing 请用 SM75 路由；作者仅在 3080 Ti 上做过 PTX 前向检查。",
        ["Gpu.AdviceUnknown"] = "未识别的型号，请自行确认路由。",
        ["Gpu.Mismatch"] = "⚠ 显卡名称与硬件 ID 不符：名称显示「{0}」，但硬件 ID {1} 属于 {2} 架构{3}。名称可能被工具修改过，这会误导驱动与游戏的功能判断。已按硬件 ID 判定为 {2}，路由取 {4}；建议恢复显卡名称后重试。",
        ["Gpu.SeriesAmpere"] = "（RTX 30 系）",
        ["Gpu.MismatchShort"] = "⚠ 名称与硬件 ID 不符，建议还原显卡名称",
        ["Gpu.RouteShort"] = "路由 {0}",
        ["Gpu.SeriesTuring"] = "（RTX 20 系）",
        ["Gpu.SeriesAda"] = "（RTX 40 系）",
        ["Gpu.SeriesBlackwell"] = "（RTX 50 系）",

        // ── 下载 ─────────────────────────────────────────────────────
        ["Fetch.Starting"] = "下载源：{0}",
        ["Fetch.Retrying"] = "下载源：{0}（第 {1} 次尝试）",
        ["Fetch.Downloading"] = "下载 {0}（{1}/{2}）",
        ["Fetch.Extracting"] = "解压 …",
        ["Fetch.Downloaded"] = "已下载 {0} MB",
        ["Fetch.DownloadedCount"] = "已下载 {0} MB（{1}/{2} 个文件）",
        ["Fetch.Updated"] = "已更新 {0} 个文件到 {1}",
        ["Fetch.PrunedStale"] = "  已移除旧版本的入口 {0}（当前版本不再发布它）",
        ["Fetch.UpdatedVersion"] = "已更新到 {0}（{1}）",
        ["Fetch.UpdatedGeneric"] = "已更新 {0} 个文件（{1}）",
        ["Fetch.SignatureOk"] = "签名校验通过",
        ["Fetch.SkippedOptional"] = "跳过可选文件 {0}：{1}",
        ["Fetch.AllFailed"] = "所有下载源均失败。\n     {0}",
        ["Fetch.Failed"] = "下载失败：{0}",
        ["Fetch.AttemptFailed"] = "[{0}] 第 {1}/{2} 次失败: {3}",
        ["Fetch.Incomplete"] = "内容不完整，缺少：{0}",
        ["Fetch.Unsigned"] = "校验失败：以下文件没有本项目的有效签名 — {0}",
        ["Fetch.Tampered"] = "校验失败：以下文件的签名摘要不匹配，内容可能已被篡改 — {0}",
        ["Fetch.DigestMismatch"] = "校验失败：以下文件的摘要与发布值不符 — {0}",
        ["Fetch.PinMismatch"] = "校验失败（镜像源）：{0}",
        ["Fetch.PinWarning"] = "警告：{0}。来源为 GitHub 官方，已接受但请留意上游是否更换证书。",
        ["Fetch.PinAccepted"] = "签名证书与记录的指纹不同（{0}）。来源为 GitHub 官方，已接受；若上游更换了证书，请更新管理器。",
        ["Fetch.PinDetail"] = "以下文件的签名证书与预期不符 — {0}",
        ["Fetch.ArchiveTooLarge"] = "压缩包过大（{0} MB），已中止。",
        ["Fetch.ArchiveTooLarge2"] = "压缩包超过大小上限，已中止。",
        ["Fetch.ContentTooLarge"] = "下载内容超过大小上限，已中止。",
        ["Fetch.BadArchive"] = "压缩包结构异常：未找到内容目录。",
        ["Fetch.EscapeAttempt"] = "文件路径指向目标目录之外。",
        ["Fetch.UrlRejected"] = "地址不允许：{0}（若使用代理或 hosts 加速，请确认系统代理已开启）",
        ["Fetch.RedirectRejected"] = "重定向目标不允许：{0}",
        ["Fetch.HttpFailed"] = "请求失败（HTTP {1}）：{0}",
        ["Fetch.ProgressFiles"] = "{0} · 文件 {1}/{2}",
        ["Fetch.ProgressArchive"] = "{0} · 归档下载",
        ["Fetch.Pause"] = "暂停",
        ["Fetch.Resume"] = "继续",
        ["Fetch.PauseTip"] = "在当前文件结束后暂停；想换下载源请直接取消后重新选择",
        ["Fetch.Cancel"] = "取消",
        ["Fetch.CancelTip"] = "中断下载。未通过校验的内容不会写入 Mod 目录，可直接换源重试",
        ["Fetch.Cancelled"] = "下载已取消。可点「下载 / 更新 Mod 文件」换其他源重试。",
        ["Fetch.RedirectNoTarget"] = "重定向缺少目标地址。",
        ["Fetch.RedirectTooMany"] = "重定向次数过多。",
        ["Fetch.UnknownFilter"] = "未识别的下载源筛选 «{0}»，改用全部源。可用值：{1}",
        ["Fetch.SourceCodeload"] = "GitHub 归档（codeload）",
        ["Fetch.SourceZipball"] = "GitHub API（zipball）",
        ["Fetch.SourceRaw"] = "GitHub 原始文件（raw）",
        ["Fetch.SourceJsDelivr"] = "jsDelivr CDN 镜像",
        ["Fetch.SourceGhProxy"] = "gh-proxy 国内加速",
        ["Fetch.SourceGhFast"] = "ghfast 国内加速",
        ["Fetch.Note.codeload"] = "单次请求，约 28 MB，通常最快",
        ["Fetch.Note.zipball"] = "与归档相同的内容，走 API 入口",
        ["Fetch.Note.raw"] = "逐个文件下载，约 75 MB，网络链路与上面不同",
        ["Fetch.Note.jsdelivr"] = "公共 CDN，GitHub 连不上时可用",
        ["Fetch.Note.ghproxy"] = "国内加速节点，实测最快；支持归档与逐文件",
        ["Fetch.Note.ghfast"] = "国内加速节点，仅逐文件下载",
        ["Fetch.FailureItem"] = "{0}：{1}",
        ["Fetch.SingleSourceFailed"] = "选定的下载源失败。\n     {0}\n\n可以换一个源重试，或选择「自动」让它依次尝试。",
        ["Fetch.PickerTitle"] = "选择下载源",
        ["Fetch.PickerPrompt"] = "从哪里获取 Mod 文件？",
        ["Fetch.PickerAuto"] = "自动（依次尝试所有源）",
        ["Fetch.PickerAutoNote"] = "推荐。某个源不可用时自动切换到下一个。",
        ["Fetch.PickerSingleNote"] = "只使用选定的源；失败不会切换到其他源。",
        ["Fetch.PickerOfficial"] = "官方",
        ["Fetch.PickerMirror"] = "镜像",
        ["Fetch.PickerDownload"] = "开始下载",
        ["Fetch.Confirm"] = "将下载 dlssg_for_sm86 的文件并写入：\n\n{0}\n\n程序会依次尝试多个下载源（GitHub 归档 / API / 原始文件，以及 jsDelivr 镜像），全部走 HTTPS，失败会自动切换源。下载后校验文件签名，通过后才落盘。\n\n继续吗？",
        ["Fetch.ConfirmTitle"] = "更新 Mod 文件",
        ["Fetch.StartLog"] = "— 从 GitHub 更新 Mod 文件",
        ["Fetch.AutoStart"] = "— 首次启动：自动检测上游版本并获取 Mod 文件 → {0}",
        ["Fetch.AutoDetected"] = "  上游最新版本：{0}",
        ["Fetch.AutoFailed"] = "自动获取未成功：{0}\n\n程序照常可用，点工具条上的「下载 / 更新 Mod 文件」可以重试。",
        ["Fetch.DoneTitle"] = "更新完成",
        ["Fetch.DoneTitleFirst"] = "获取完成",
        ["Fetch.DoneBody"] = "{0}\n\n如果 Mod 有新的配置项，可在各游戏的配置面板里重新部署以写入。",
        ["Fetch.DoneBodyFirst"] = "{0}\n\n接下来点「扫描 Steam 库」或「添加游戏…」就能开始部署了。",
        ["Fetch.NotReadyLog"] = "Mod 文件源未就绪：尚未获取 mod 文件。点「下载 / 更新 Mod 文件」自动下载。",
        ["Fetch.IncompleteLog"] = "Mod 文件源不完整：{0}",

        // ── 添加代理 DLL（用户自备入口）──────────────────────────────
        ["Proxy.AddTitle"] = "添加代理 DLL",
        ["Proxy.AddFilter"] = "DLL 文件 (*.dll)|*.dll",
        ["Proxy.AddNeedSource"] = "请先获取 Mod 文件（工具条上的「下载 / 更新 Mod 文件」），代理 DLL 与它们存放在一起。",
        ["Proxy.AddNeedDll"] = "请选择一个 .dll 文件。",
        ["Proxy.AddFileMissing"] = "文件不存在：{0}",
        ["Proxy.AddReserved"] = "「{0}」是本项目自带的入口名，不能覆盖。",
        ["Proxy.AddUnknownName"] = "「{0}」不在已知入口名列表里（version / winmm / dinput8 / winhttp / dxgi / d3d12）。游戏通常不会加载别的名字，部署后很可能没有任何效果。\n\n仍要添加吗？",
        ["Proxy.Added"] = "已添加代理入口 {0} → {1}",
        ["Proxy.AddedFile"] = "  已写入 {0}（{1} KB）",
        ["Proxy.AddedSigner"] = "  签名者：{0}",
        ["Proxy.AddedUnsigned"] = "  未签名或签名无效（本地文件的来源由你自己确认）",
        ["Proxy.AddReplaced"] = "  已替换同名的本地代理 {0}",
        ["Proxy.AddFailed"] = "添加失败：{0}",
        ["Proxy.ImportedSuffix"] = "（附加入口）",

        // ── Mod 文件源 ───────────────────────────────────────────────
        ["ModSource.DirMissing"] = "目录不存在",
        ["ModSource.IniMissing"] = "缺少 {0}",
        ["ModSource.NoDll"] = "未找到任何代理 DLL（version.dll 或 altnative\\*.dll）",
        ["ModSource.IniMissingAndNoDll"] = "缺少 {0}，且未找到任何代理 DLL",
        ["ModSource.IniMissingAt"] = "缺少 {0}",
        ["ModSource.UnknownVersion"] = "未知",

        // ── Shell 路径校验（内部原因说明）────────────────────────────
        ["Path.Empty"] = "路径为空",
        ["Path.TooLong"] = "路径过长",
        ["Path.Whitespace"] = "路径首尾有空白字符",
        ["Path.ControlChar"] = "路径含控制字符",
        ["Path.Quote"] = "路径含引号",
        ["Path.NotAbsolute"] = "路径不是绝对路径",
        ["Path.Invalid"] = "路径无效：{0}",

        // ── 页面导航（界面结构）──────────────────────────────────────
        ["Nav.Primary"] = "主要",
        ["Nav.Advanced"] = "高级",
        ["Nav.Dashboard"] = "总览",
        ["Nav.Library"] = "游戏库",
        ["Nav.GameDetails"] = "游戏详情",
        ["Nav.Updates"] = "更新",
        ["Nav.Downloads"] = "下载",
        ["Nav.Diagnostics"] = "诊断",
        ["Nav.Settings"] = "设置",

        ["Page.Dashboard.Purpose"] = "这台机器现在是什么状态、下一步该做什么。",
        ["Page.Library.Purpose"] = "已找到的游戏，以及每个游戏当前的状态。",
        ["Page.GameDetails.Purpose"] = "选中游戏要做什么，以及结果如何。",
        ["Page.Updates.Purpose"] = "本软件与补丁的更新。",
        ["Page.Downloads.Purpose"] = "正在进行的传输与已完成的历史。",
        ["Page.Diagnostics.Purpose"] = "日志、检测结果与兼容性记录。",
        ["Page.Settings.Purpose"] = "语言、主题、代理、Provider 与频道。",
        ["Page.Placeholder"] = "此页的内容仍在建设中。下面的内容来自已经就绪的核心服务。",
        ["Page.AdvancedNote"] = "高级功能默认折叠：Proxy、ASI、图形 API、NVIDIA Profile、Flip Pacing、Low Latency、Provider、发布频道、日志。平台的高级项不会出现在首次使用的主流程里。",
        ["Page.Dashboard.Machine"] = "本机",
        ["Page.Dashboard.NextStep"] = "下一步",
        ["Page.Dashboard.NoGamesTitle"] = "还没有游戏",
        ["Page.Dashboard.NoGamesBody"] = "先扫描 Steam 库或手动添加游戏，然后在游戏库里选择它并自动配置。",
        ["Path.Missing"] = "路径不存在",

        // ── 配置确认（未知兼容性）────────────────────────────────────
        ["Deploy.ConfirmTitle"] = "需要你确认",
        ["Deploy.ConfirmBody"] = "「{0}」的配置需要你确认后才能继续。\n\n{1}\n\n确认继续吗？（这只表示你知情，不代表该组合已被验证。）",
        ["Deploy.ConfirmDeclined"] = "已取消「{0}」的配置，未写入任何内容。",
        ["Path.NotFile"] = "不是文件",

        // ── Provider 选择 ────────────────────────────────────────────
        ["Toolbar.Provider"] = "配置方式",
        ["Toolbar.ProviderTip"] = "选择用哪个 Provider 配置游戏。内置 dlssg-sm86 是默认值；切换后对之后的操作生效。",

        // ── 批量部署的计划摘要 ───────────────────────────────────────
        ["Batch.PlanHeader"] = "本次计划摘要：",
        ["Batch.PlanBlocked"] = "以下 {0} 个游戏当前无法部署（计划被阻止）：",
        ["Batch.PlanNeedsConfirm"] = "以下 {0} 个游戏需要你明确确认后才能继续：",
        ["Path.NotExecutable"] = "不是可执行文件",

        // ── 错误与异常 ───────────────────────────────────────────────
        ["Error.Unhandled"] = "操作过程中出现未处理的错误：\n\n{0}\n\n详细信息已写入日志。",
        ["Error.UnhandledTitle"] = "DLSSG 30 系管理器",
        ["Error.FetchFailed"] = "获取 Mod 文件失败：\n\n{0}\n\n可稍后在界面上重试。",
        ["Error.FetchException"] = "获取 Mod 文件时出错：\n\n{0}",
        ["Error.ElevationCancelled"] = "提权被取消或失败。也可以右键 exe 选择「以管理员身份运行」。",
        ["Error.DirNotFound"] = "目录不存在。",
        ["Error.DirOpenFailed"] = "目录不存在或无法打开。",
        ["Error.LaunchFailed"] = "启动失败：请先设置有效的启动程序路径。",
        ["Error.NoModLog"] = "还没有 Mod 日志。把该游戏的日志级别设为 2，启动游戏后即可生成。",
        ["Error.LogOpened"] = "已打开最新日志：{0}",
        ["Error.CannotOpenDataDir"] = "无法打开数据目录：{0}",
        ["Error.Launched"] = "已启动 {0}",
    };
}
